### ISSUE TITLE
Pressing TAB jumps multiple results at a time

### ISSUE THREAD

**Issue by bb2020** [jchafik/google-search-shortcuts#27]
Version = 1.1.14
:cry:

**Comment by ducalpha** [comment]
I have the same problem. Using arrow keys (up and down) to navigate jumps multiple results at a time.

**Comment by jchafik** [comment]
Google selectors have been updated. A new release has been pushed and should be available shortly.

**Comment by Newgap** [comment]
Doesn't seems to work on firefox. It skips all the way down to related searches and page numbers.

**Comment by buschtoens** [comment]
@Newgap #29 should fix this.

**Comment by Newgap** [comment]
Is the fix for the issue #29 is in the version 1.1.15. If yes, than it didn't fix the problem :(

**Comment by buschtoens** [comment]
@Newgap Nope. The PR is still not merged, so it's unfortunately also not in the latest release.
