### ISSUE TITLE
Focus returning to search bar when typing while focused on currency conversion input fields.

### ISSUE THREAD

**Issue by xnick** [jchafik/google-search-shortcuts#4]
For example, after the search "gbp to eur", I cannot change the values being converted. The focus immediately returns to the search bar. 

It looks like what you did to fix #1 didn't work for this case. 

I have not encountered it in any other cases (translate and calculator work fine).

**Comment by jchafik** [comment]
Thank you. This has been addressed.

**Comment by v1k45** [comment]
@jchafik this update is not pushed on firefox. I can still reproduce this issue on Firefox.

**Comment by jchafik** [comment]
This has been pushed to Firefox. It should be available shortly.
