### ISSUE TITLE
Shortcuts are binded too slow 

### ISSUE THREAD

**Issue by OrDuan** [jchafik/google-search-shortcuts#9]
Hey,
If I'm trying to click the down arrow too early the page scrolls down a bit, instead of showing the arrow head, then after about a second~ the shortcuts are getting binded and the arrow appears.
![Peek 2019-04-30 14-06](https://user-images.githubusercontent.com/5006049/56957933-660a8800-6b51-11e9-90df-e74824096c8b.gif)

I guess the extension has the default behavior to start on  idle state, this could be change, and then observe/onload trigger the binding when the body is ready.

I hope I was clear, I can provide more info or try to make a PR

**Comment by jchafik** [comment]
I'm unable to reproduce. Since this issue was opened so long ago, I'm going to assume that the binding issue has been resolved in one of the releases that has since been published. If it's not, please reopen.

**Comment by HackingThis** [comment]
Hey! Thanks for reaching out, it is still an issue - if you spam the down arrow when the page loads, you will see the same behavior.

I would like to quickly be able to use the error/enter key and there is like 700ms delay
